#!/usr/bin/env python3
"""
Small utility for making anonymous gists from command line
"""

import os
import json
import argparse
import requests

BASE_DIR = os.getcwd()
ENDPOINT = "https://api.github.com/gists"


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Utility for making anonymous gists")
    parser.add_argument("filename", help="Name of file to make into gist")
    parser.add_argument("-d", "--description", help="description for gist")
    parser.add_argument("-r", "--raw", action="store_true", help="fetch raw link")
    parser.add_argument("-s", "--secret", action="store_true",
                        help="hide gist from search engines")
    args = parser.parse_args()

    if args.secret:
        request_data = { "public": False }
    else:
        request_data = { "public": True }

    if args.description:
        request_data["description"] = args.description

    if "/" not in args.filename:
        filename = args.filename
    else:
        filename = args.filename[args.filename.rfind("/") + 1:]

    request_data["files"] = { filename: { "content": None } }
    try:
        with open("{}/{}".format(BASE_DIR, args.filename), 'r') as content_file:
            request_data["files"][filename]["content"] = content_file.read()
    except IOError:
        print("An error occured when opening the file")
        exit(1)


    r = requests.post(ENDPOINT, data=json.dumps(request_data))

    try:
        as_json = r.json()
        if 'html_url' in as_json:
            if args.raw:
                print(as_json["files"][filename]["raw_url"])
            else:
                print(as_json['html_url'])
        else:
            print(as_json['message'].rstrip())
    except:
        print("An error occured")
